---
title: "Titanic_project"
author: "Qinwen Yang"
date: "11/15/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Ask Question:
1. Male or Female, which sex have more survive in this disaster?
2. Does the survival related to people's Pclass, Sibsp, or Parch?


```{r}
#Read Data:
gender_sub <- read.csv('gender_submission.csv', header = TRUE)
gender_sub

train_titanic <- read.csv('train.csv', header = TRUE, stringsAsFactors = FALSE)
dim(train_titanic)

test_titanic <- read.csv('test.csv', header = TRUE, stringsAsFactors = FALSE)
dim(test_titanic)


#Combine train and test dataset vertically to find missing value.

##First: Create a new column in each dataset to recognise which is trainset, which testset.
train_titanic$IsTrainSet <- TRUE
test_titanic$IsTrainSet <- FALSE
##Since they have different number of columns for each two datasets
ncol(train_titanic)#13
ncol(test_titanic)#12
names(train_titanic)
names(test_titanic)
##We found there's one column missing in test dataset which is called Survived. Thus we need to create a column in test dataset named Survived and filled with NA.
test_titanic$Survived <- NA
##Combine:
titanic <- rbind(train_titanic, test_titanic)
head(titanic)
tail(titanic)
table(titanic$IsTrainSet)
sum(is.na(titanic))
table(is.na(titanic$Age))
#replace missing value for age column to median
median.Age <- median(titanic$Age, na.rm = TRUE)
titanic[is.na(titanic$Age), "Age"] <- median.Age
table(is.na(titanic$Age)) #Non missing value in Age column
table(is.na(titanic$Fare))
median.fare <- median(titanic$Fare, na.rm = TRUE)
titanic[is.na(titanic$Fare), "Fare"] <- median.fare
table(is.na(titanic$Embarked))
titanic[!complete.cases(titanic), ]

train_titanic <- titanic[titanic$IsTrainSet == TRUE,]
test_titanic <- titanic[titanic$IsTrainSet == FALSE,]
sum(is.na(train_titanic)) #no missing value for train dataset
str(train_titanic)

library(ggplot2)
library(dplyr)
train_titanic <- train_titanic[,-c(1,9,11,12,13)]
train_titanic$Survived <- as.factor(train_titanic$Survived)
train_titanic$Pclass <- as.factor(train_titanic$Pclass)
train_titanic %>% ggplot(aes(x=Sex, fill=Survived))+geom_bar()
train_titanic %>% ggplot(aes(x=Pclass, fill = Survived))+geom_bar()
train_titanic %>% ggplot(aes(x=SibSp, fill = Survived))+geom_bar()

library(GGally)
install.packages('psych')
library(psych)
pairs.panels(train_titanic[,c(5,6,7,8)], density=TRUE, ellipses = TRUE)
```




